function mountLearningJourney(host){
const KEY="bbx2-learning-journey",PASS=80;
const levels=[
{id:"grammar",title:"Grammar Garden",short:"Grammar",type:"quiz",lesson:"Meet the building blocks of a clear sentence: start with a capital, choose the right verb, and finish with punctuation. Your creature will help you spot each one.",tip:"Look for the subject first. Who is doing the action?",questions:[
{q:"Choose the sentence with correct capitalization and punctuation.",options:["my creature can fly.","My creature can fly.","My creature can fly"],a:1},
{q:"Choose the correct verb: She ___ a red hat.",options:["wear","wears","wearing"],a:1},
{q:"Which word is a naming word (noun)?",options:["quickly","dragon","jump"],a:1},
{q:"Complete the sentence: They ___ playing.",options:["is","am","are"],a:2},
{q:"Choose the correct sentence.",options:["I can run, but I cannot fly.","i can run but i cannot fly","I can runs but cannot fly."],a:0}]},
{id:"sentences",title:"Sentence Studio",short:"Sentences",type:"writing",lesson:"Build one strong sentence about your creature. A sentence begins with a capital letter, shares one complete idea, and ends with punctuation.",tip:"Try saying your sentence out loud. Does it sound complete?",tipline:"Write at least six words. Include both ?My creature? and ?I can?.",checks:["At least 6 words","Begins with a capital letter","Ends with . ! or ?","Includes ?My creature?","Includes ?I can?"]},
{id:"story",title:"Story Chapter",short:"Story",type:"story",lesson:"This is your final chapter. Plan a beginning, a few events, and an ending. Connect ideas with words such as first, then, because, and finally.",tip:"Your creature is ready to guide the story. Give it a beginning, a problem, and a happy ending.",tipline:"Write a short story of at least 40 words with three or more sentences.",checks:["At least 40 words","At least 3 complete sentences","Each sentence starts with a capital","Sentences end with punctuation","Uses a story connector (first, then, because, finally, after)"]}
];
let progress;try{progress=JSON.parse(localStorage.getItem(KEY))||{}}catch{progress={}}
progress.started=progress.started||{};progress.completed=progress.completed||{};progress.scores=progress.scores||{};progress.answers=progress.answers||{};progress.draft=progress.draft||"";
let active=progress.active||"grammar",view="lesson",notice="",lastScore=null,lastPassed=false;
const allowed=id=>id==="grammar"||id==="sentences"&&progress.completed.grammar||id==="story"&&progress.completed.sentences;
function save(){progress.active=active;try{localStorage.setItem(KEY,JSON.stringify(progress))}catch{}}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){const stage=levels.find(x=>x.id===active)||levels[0];if(!allowed(stage.id))active="grammar";const current=levels.find(x=>x.id===active);
host.innerHTML='<div class="play-grid"><section class="play-main"><header class="play-heading"><p class="eyebrow">PLAY ? YOUR LEARNING JOURNEY</p><h2>Learn it. Try it. Master it.</h2><p>Pass each checkpoint with 80% or more to unlock the next stage.</p></header><nav class="level-tabs" aria-label="Learning stages">'+levels.map((x,i)=>'<button class="level-tab '+(x.id===active?"current ":"")+(progress.completed[x.id]?"passed":"")+'" data-level="'+x.id+'" '+(allowed(x.id)?"":"disabled")+'><span>Stage '+(i+1)+'</span><b>'+x.short+'</b><small>'+(progress.completed[x.id]?"Passed "+progress.scores[x.id]+"%":allowed(x.id)?"Unlocked":"Locked")+'</small></button>').join("")+'</nav><div class="lesson-card"><p class="eyebrow">'+(view==="lesson"?"LESSON":"CHECKPOINT")+' ? '+current.title.toUpperCase()+'</p><h3>'+current.title+'</h3><p>'+current.lesson+'</p>'+(current.tipline?'<p class="instruction">'+current.tipline+'</p>':"")+renderActivity(current)+'<p class="play-message" role="status">'+safe(notice)+'</p></div></section><aside class="guide-card"><div class="guide-avatar"><div class="avatar-face"><i></i><i></i><b></b></div><span>Character art placeholder</span></div><p class="eyebrow">YOUR ADVENTURE GUIDE</p><h3>Creature Guide</h3><p>'+current.tip+'</p><div class="guide-tip"><b>Guide tip</b><br>Take your time. You can retry a checkpoint whenever you need.</div><p class="guide-score">Mastery pass mark: <strong>'+PASS+'%</strong></p></aside></div>';
host.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{if(!allowed(b.dataset.level))return;active=b.dataset.level;view="lesson";notice="";lastScore=null;save();render()});
const begin=host.querySelector("#beginCheckpoint");if(begin)begin.onclick=()=>{progress.started[active]=true;view="activity";notice="";save();render()};
host.querySelectorAll("[data-answer]").forEach(r=>r.onchange=()=>{progress.answers[r.name]=Number(r.value);save()});
const quiz=host.querySelector("#submitQuiz");if(quiz)quiz.onclick=submitQuiz;
const draft=host.querySelector("#writingAnswer");if(draft)draft.oninput=()=>{progress.draft=draft.value;save()};
const submit=host.querySelector("#submitWriting");if(submit)submit.onclick=submitWriting;
const next=host.querySelector("#continueStage");if(next)next.onclick=()=>{active=active==="grammar"?"sentences":"story";view="lesson";notice="";lastScore=null;save();render()};
const retry=host.querySelector("#retry");if(retry)retry.onclick=()=>{view="activity";notice="";lastScore=null;render()};
}
function renderActivity(s){if(view==="lesson")return '<button class="btn begin-checkpoint" id="beginCheckpoint">'+(progress.started[active]?"Continue to checkpoint":"I understand - begin checkpoint")+'</button>';
if(s.type==="quiz")return '<p>Answer all five questions. You need four correct to pass.</p><div class="quiz-list">'+s.questions.map((q,i)=>'<fieldset class="quiz-question"><legend>'+(i+1)+'. '+q.q+'</legend>'+q.options.map((o,j)=>'<label><input type="radio" name="q'+i+'" data-answer value="'+j+'" '+(progress.answers["q"+i]===j?"checked":"")+'> '+o+'</label>').join("")+'</fieldset>').join("")+'</div><button class="btn" id="submitQuiz">Check my answers</button>'+resultMarkup(s);
return '<p>'+s.tipline+'</p><textarea id="writingAnswer" rows="'+(s.type==="story"?10:5)+'" placeholder="'+(s.type==="story"?"Write your creature's story here...":"Write your sentence here...")+'">'+safe(progress.draft)+'</textarea><ul class="rubric">'+s.checks.map(x=>'<li>'+x+'</li>').join("")+'</ul><button class="btn" id="submitWriting">Score my writing</button>'+resultMarkup(s)}
function resultMarkup(s){if(lastScore===null)return "";const passed=lastPassed;return '<div class="score-result '+(passed?"passed":"retry-result")+'"><h4>'+(passed?"Checkpoint passed!":"Not quite - try again")+'</h4><p>Your score: <strong>'+lastScore+'%</strong>. '+(passed?"The next stage is unlocked.":"You need at least "+PASS+"%. Review the lesson and give it another try.")+'</p>'+(passed&&active!=="story"?'<button class="btn secondary" id="continueStage">Continue to '+(active==="grammar"?"sentence writing":"the Story Chapter")+'</button>':passed?'<p>You completed the final chapter. Your creature is proud of you!</p>':'<button class="btn secondary" id="retry">Try checkpoint again</button>')+'</div>'}
function finish(score){lastScore=score;lastPassed=score>=PASS;progress.scores[active]=score;if(lastPassed){progress.completed[active]=true;progress.xp=(progress.xp||0)+score;notice="Mastery recorded and saved on this device."}else notice="Checkpoint not passed yet. Read the lesson and retry.";save();render()}
function submitQuiz(){const s=levels.find(x=>x.id===active);let correct=0;for(let i=0;i<s.questions.length;i++){if(progress.answers["q"+i]===undefined){notice="Answer all five questions before scoring.";render();return}if(progress.answers["q"+i]===s.questions[i].a)correct++}finish(Math.round(correct/s.questions.length*100))}
function scoreWriting(text,s){const words=text.trim().split(/\s+/).filter(Boolean),sentences=(text.match(/[.!?]+(?:\s|$)/g)||[]).length,checks=s.type==="story"?[words.length>=40,sentences>=3,/^[A-Z]/.test(text.trim())&&/[.!?]\s+[A-Z]/.test(text),/[.!?]$/.test(text.trim()),/\b(first|then|because|finally|after)\b/i.test(text)]:[words.length>=6,/^[A-Z]/.test(text.trim()),/[.!?]$/.test(text.trim()),/\bmy creature\b/i.test(text),/\bi can\b/i.test(text)];return Math.round(checks.filter(Boolean).length/checks.length*100)}
function submitWriting(){const text=host.querySelector("#writingAnswer").value.trim();progress.draft=text;save();if(!text){notice="Write your response before scoring.";render();return}finish(scoreWriting(text,levels.find(x=>x.id===active)))}
render()
}


function profileSafe(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/\x27/g,"&#39;")}
function renderPlayerProfile(){const root=document.querySelector("#screen-profile");if(!root)return;let creatures=[],progress={};try{creatures=JSON.parse(localStorage.getItem("bbx2-player-creatures")||"[]")}catch{}try{progress=JSON.parse(localStorage.getItem("bbx2-learning-journey")||"{}")}catch{}const name=localStorage.getItem("bbx2-player-name")||"Player";const passed=["grammar","sentences","story"].filter(x=>progress.completed&&progress.completed[x]).length;const cards=creatures.map(c=>{const n=profileSafe(c.name);return "<article class=\"player-creature\"><div class=\"player-creature-icon\">"+(c.icon?"<img src=\""+c.icon+"\" alt=\""+n+" character icon\">":"<span>Creature</span>")+"</div><h3>"+n+"</h3><p>"+profileSafe(c.animal)+" / "+profileSafe(c.personality)+"</p></article>"}).join("");root.innerHTML="<section class=\"profile-heading\"><p class=\"eyebrow\">YOUR ADVENTURE CARD</p><h2>Player Profile</h2><label for=\"playerName\">Your name</label><input id=\"playerName\" maxlength=\"24\" value=\""+profileSafe(name)+"\" placeholder=\"Enter your name\"><div class=\"profile-stats\"><div><strong>"+passed+" / 3</strong><span>stages mastered</span></div><div><strong>"+(progress.xp||0)+"</strong><span>learning points</span></div><div><strong>"+creatures.length+"</strong><span>creatures created</span></div></div></section><section class=\"profile-collection\"><p class=\"eyebrow\">YOUR CREATURE COLLECTION</p><h2>Character icons</h2>"+(cards?"<div class=\"player-creature-grid\">"+cards+"</div>":"<div class=\"empty-collection\"><div>?</div><h3>Your first character is waiting</h3><p>Create a creature and its icon will appear here automatically.</p><a class=\"home-start\" href=\"#create\">Create a creature</a></div>")+"</section>";root.querySelector("#playerName").addEventListener("input",e=>localStorage.setItem("bbx2-player-name",e.target.value.trim()))}

window.addEventListener("DOMContentLoaded",()=>{const file=location.pathname.split("/").pop()||"index.html";document.querySelectorAll("#pageNav a").forEach(a=>{if(a.dataset.file===file){a.classList.add("active");a.setAttribute("aria-current","page")}});const play=document.querySelector("#learningJourney");if(play)mountLearningJourney(play);if(document.querySelector("#screen-profile"))renderPlayerProfile()});
