const selections={animal:null,bodyparts:[],clothes:null};
const instructions=[{task:"Write a sentence.\nStart with: I’ve got… Then write a number and a body part.",example:"Example: I’ve got two hands."},{task:"Write a sentence about your creature’s clothes.\nUse: This is my… or These are my…",example:"Example: This is my green hat."},{task:"Imagine your creature can do something special.\nWrite: I can… or I can’t…",example:"Example: I can jump very high."}];
const loadingMessages=["🧠 Mixing ideas in the Brain Kitchen…","🎨 Painting your creature…","✨ Giving your idea a little magic…","🚀 Your imagination is taking off…"];
const errorMessages=["Oops! The Brain Machine needs a moment. Please try again.","Our idea gears got stuck. Give it another go!","The picture did not arrive. Please try again."];
const BACKEND="https://brainboom-cards.vercel.app";
let requestId=0;
function selectCard(el){const cat=el.closest('.category').dataset.category,val=el.dataset.value;if(cat==='bodyparts'){el.classList.toggle('selected');selections.bodyparts=el.classList.contains('selected')?[...selections.bodyparts,val]:selections.bodyparts.filter(x=>x!==val)}else{el.closest('.category').querySelectorAll('.card').forEach(c=>c.classList.remove('selected'));el.classList.add('selected');selections[cat]=val}updateSummary();saveState();if(selections.animal&&selections.bodyparts.length&&selections.clothes)showCombo()}
function updateSummary(){const items=[selections.animal,...selections.bodyparts,selections.clothes].filter(Boolean);document.getElementById('selectionSummary').textContent=items.length?`Your choices: ${items.join(' · ')}`:'Choose one card from each category.'}
function clearSelections(){document.querySelectorAll('.card.selected').forEach(c=>c.classList.remove('selected'));selections.animal=null;selections.bodyparts=[];selections.clothes=null;requestId++;document.getElementById('comboImage').style.display='none';document.getElementById('comboMessage').textContent='Your original BrainBoom image will appear here when all three categories are selected.';updateSummary();saveState()}
function newInstruction(){const i=instructions[Math.floor(Math.random()*instructions.length)];document.getElementById('instruction').textContent=i.task;document.getElementById('sentence').placeholder=i.example}
async function showCombo(){const id=++requestId;const parts=selections.bodyparts.map(bp=>`${Math.floor(Math.random()*3)+3} ${bp}`).join(', ');const prompt=`A clear, detailed educational illustration showing a ${selections.animal} with ${parts}, wearing ${selections.clothes}. Friendly child-safe fantasy creature, clean uncluttered background, easy to understand, full body, centered. Not cartoonish, but playful and informative.`;const img=document.getElementById('comboImage'),msg=document.getElementById('comboMessage');msg.textContent=loadingMessages[Math.floor(Math.random()*loadingMessages.length)];img.style.display='none';try{const r=await fetch(`${BACKEND}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});if(!r.ok)throw new Error(await r.text());const data=await r.json();const base64=data.imageBase64||data.base64||data.artifacts?.[0]?.base64;if(!base64)throw new Error('No image returned');if(id!==requestId)return;img.src=`data:image/png;base64,${base64}`;img.style.display='block';msg.textContent='✨ Your BrainBoom creation is ready!'}catch(e){console.error(e);if(id===requestId)msg.textContent=errorMessages[Math.floor(Math.random()*errorMessages.length)]}}
function saveState(){try{localStorage.setItem('bbx2-part1-state',JSON.stringify(selections))}catch(e){}}
function restoreState(){try{const saved=JSON.parse(localStorage.getItem('bbx2-part1-state'));if(!saved)return;Object.assign(selections,{animal:saved.animal||null,bodyparts:Array.isArray(saved.bodyparts)?saved.bodyparts:[],clothes:saved.clothes||null});document.querySelectorAll('.card').forEach(c=>{const cat=c.closest('.category').dataset.category,val=c.dataset.value;c.classList.toggle('selected',cat==='bodyparts'?selections.bodyparts.includes(val):selections[cat]===val)});updateSummary()}catch(e){console.warn(e)}}
window.addEventListener('DOMContentLoaded',restoreState);window.selectCard=selectCard;window.newInstruction=newInstruction;window.clearSelections=clearSelections;window.showCombo=showCombo;
